#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=dejagnu-1.5
tar -xf ${basename}.tar.gz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.gz"
cd ${basename}
##### Code things

#Configure
./configure --prefix=/tools  	2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

#MAKE CHECK
#make check

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
