#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
tar -jxf gcc-4.7.2.tar.bz2 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar gcc-4.7.2.tar.bz2"
cd gcc-4.7.2 
##### Core things

cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
  `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/include-fixed/limits.h

cp -v gcc/Makefile.in{,.tmp}
sed 's/^T_CFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp \
  > gcc/Makefile.in

for file in \
 $(find gcc/config -name linux64.h -o -name linux.h -o -name sysv4.h)
do
  cp -uv $file{,.orig}
  sed -e 's@/lib\(64\)\?\(32\)\?/ld@/tools&@g' \
  -e 's@/usr@/tools@g' $file.orig > $file
  echo '
#undef STANDARD_STARTFILE_PREFIX_1
#undef STANDARD_STARTFILE_PREFIX_2
#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"
#define STANDARD_STARTFILE_PREFIX_2 ""' >> $file
  touch $file.orig
done


tar -Jxf ../mpfr-3.1.1.tar.xz
errorMsg $? "Failed to untar mpfr-3.1.1.tar.xz"
mv -v mpfr-3.1.1 mpfr 2>&1 >> ${DFILE}
tar -Jxf ../gmp-5.1.1.tar.xz
errorMsg $? "Failed to untar gmp-5.1.1.tar.xz"
mv -v gmp-5.1.1 gmp  2>&1 >> ${DFILE}
tar -zxf ../mpc-1.0.1.tar.gz
errorMsg $? "Failed to untar gmp-5.1.1.tar.xz"
mv -v mpc-1.0.1 mpc 2>&1 >> ${DFILE}

#Tuning
sed -i 's/BUILD_INFO=info/BUILD_INFO=/' gcc/configure
mkdir -v ../gcc-build 2>&1 >> ${DFILE}
cd ../gcc-build

#Configure
CC=$LFS_TGT-gcc \
AR=$LFS_TGT-ar                  \
RANLIB=$LFS_TGT-ranlib          \
../gcc-4.7.2/configure          \
    --prefix=/tools             \
    --with-local-prefix=/tools  \
    --with-native-system-header-dir=/tools/include \
    --enable-clocale=gnu        \
    --enable-shared             \
    --enable-threads=posix      \
    --enable-__cxa_atexit       \
    --enable-languages=c,c++    \
    --disable-libstdcxx-pch     \
    --disable-multilib          \
    --disable-bootstrap         \
    --disable-libgomp           \
    --with-mpfr-include=$(pwd)/../gcc-4.7.2/mpfr/src \
    --with-mpfr-lib=$(pwd)/mpfr/src/.libs  2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure gcc-4.7.2"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make gcc-4.7.2"


make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install gcc-4.7.2"
ln -sv gcc /tools/bin/cc

# Do some testing
echo 'main(){}' > dummy.c
cc dummy.c
readelf -l a.out | grep ': /tools'
result=`readelf -l a.out | grep -c ': /tools'`
if [ $result -eq 0 ];then
        errorMsg 1 "GLibC Test Failed"
fi
rm -v dummy.c a.out
#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf gcc-build 2>&1 >> ${DFILE}
rm -Rf gcc-4.7.2 2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
