#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=gettext-0.18.2
tar -xf ${basename}.tar.gz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.gz"
cd ${basename}
##### Core things
cd gettext-tools
EMACS="no" ./configure --prefix=/tools --disable-shared

#Configure
make -C gnulib-lib  2>&1 >> ${DFILE}
errorMsg $? "Failed to Make1 ${basename}"
make -C src msgfmt	2>&1 >> ${DFILE}
errorMsg $? "Failed to Make2 ${basename}"

cp -v src/msgfmt /tools/bin 2>&1 >> ${DFILE}


#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
