#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
tar -Jxf linux-3.8.1.tar.xz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar linux-3.8.1.tar.xz"
cd linux-3.8.1
##### Code things
make mrproper 2>&1 >> ${DFILE}
make headers_check 2>&1 >> ${DFILE}
make INSTALL_HDR_PATH=dest headers_install 2>&1 >> ${DFILE}
cp -rv dest/include/* /tools/include 2>&1 >> ${DFILE}

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf linux-3.8.1 2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
