#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

start_time=`date +%s`

cat > /etc/hosts << "EOF"
# Begin /etc/hosts (network card version)

127.0.0.1 localhost

# End /etc/hosts (network card version)
EOF

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
