#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

start_time=`date +%s`

cd /etc/sysconfig/
cat > ifconfig.eth0 << "EOF"
ONBOOT=yes
IFACE=eth0
SERVICE=ipv4-static
IP=192.168.1.1
GATEWAY=192.168.1.2
PREFIX=24
BROADCAST=192.168.1.255
EOF
cd -

cat > /etc/resolv.conf << "EOF"
# Begin /etc/resolv.conf

domain nfvo
nameserver 8.8.8.8

# End /etc/resolv.conf
EOF

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
