#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=coreutils-8.21
tar -Jxf ${basename}.tar.xz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.xz"
cd ${basename}
##### Core things

#Patch 
patch -Np1 -i ../coreutils-8.21-i18n-1.patch 2>&1 >> ${DFILE}

#Configure
FORCE_UNSAFE_CONFIGURE=1 ./configure \
            --prefix=/usr         \
            --libexecdir=/usr/lib \
            --enable-no-install-program=kill,uptime 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make NON_ROOT_USERNAME=nobody check-root
# echo "dummy:x:1000:nobody" >> /etc/group
# chown -Rv nobody .
# su nobody -s /bin/bash \
#          -c "PATH=$PATH make RUN_EXPENSIVE_TESTS=yes check"
# sed -i '/dummy/d' /etc/group

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

mv -v /usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} /bin 2>&1 >> ${DFILE}
mv -v /usr/bin/{false,ln,ls,mkdir,mknod,mv,pwd,rm} /bin 2>&1 >> ${DFILE}
mv -v /usr/bin/{rmdir,stty,sync,true,uname,test,[} /bin 2>&1 >> ${DFILE}
mv -v /usr/bin/chroot /usr/sbin 2>&1 >> ${DFILE}
mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8 2>&1 >> ${DFILE}
sed -i s/\"1\"/\"8\"/1 /usr/share/man/man8/chroot.8 
mv -v /usr/bin/{head,sleep,nice} /bin 2>&1 >> ${DFILE}

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
