#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=flex-2.5.37
tar -jxf ${basename}.tar.bz2 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.bz2"
cd ${basename}
##### Core things

#PATCH
patch -Np1 -i ../flex-2.5.37-bison-2.6.1-1.patch 2>&1 >> ${DFILE}
#Configure
./configure --prefix=/usr             \
            --docdir=/usr/share/doc/flex-2.5.37 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make check

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

ln -sv libfl.a /usr/lib/libl.a
cat > /usr/bin/lex << "EOF"
#!/bin/sh
# Begin /usr/bin/lex

exec /usr/bin/flex -l "$@"

# End /usr/bin/lex
EOF
chmod -v 755 /usr/bin/lex

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
