#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=inetutils-1.9.1
tar -xf ${basename}.tar.gz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.gz"
cd ${basename}
##### Core things
sed -i -e '/gets is a/d' lib/stdio.in.h

#Configure
./configure --prefix=/usr  \
    --libexecdir=/usr/sbin \
    --localstatedir=/var   \
    --disable-ifconfig     \
    --disable-logger       \
    --disable-syslogd      \
    --disable-whois        \
    --disable-servers 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make check

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

mv -v /usr/bin/{hostname,ping,ping6,traceroute} /bin 2>&1 >> ${DFILE}
#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
