#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=iproute2-3.8.0
tar -Jxf ${basename}.tar.xz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.xz"
cd ${basename}
##### Core things
sed -i '/^TARGETS/s@arpd@@g' misc/Makefile
sed -i /ARPD/d Makefile
sed -i 's/arpd.8//' man/man8/Makefile
sed -i 's/-Werror//' Makefile

#Make
make DESTDIR= 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"


make DESTDIR=              \
     MANDIR=/usr/share/man \
     DOCDIR=/usr/share/doc/iproute2-3.8.0 install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"


#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
