#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=linux-3.8.1
tar -Jxf ${basename}.tar.xz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.xz"
cd ${basename}
##### Core things
make mrproper 2>&1 >> ${DFILE}
make headers_check
make INSTALL_HDR_PATH=dest headers_install
find dest/include \( -name .install -o -name ..install.cmd \) -delete
cp -rv dest/include/* /usr/include 2>&1 >> ${DFILE}

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
