#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=ncurses-5.9
tar -xf ${basename}.tar.gz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.gz"
cd ${basename}
##### Code things

#Configure
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --enable-pc-files       \
            --enable-widec 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
#

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

mv -v /usr/lib/libncursesw.so.5* /lib  2>&1 >> ${DFILE}
ln -sfv ../../lib/libncursesw.so.5 /usr/lib/libncursesw.so  2>&1 >> ${DFILE}
for lib in ncurses form panel menu ; do
    rm -vf                    /usr/lib/lib${lib}.so  2>&1 >> ${DFILE}
    echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so
    ln -sfv lib${lib}w.a      /usr/lib/lib${lib}.a  2>&1 >> ${DFILE}
    ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc  2>&1 >> ${DFILE}
done

ln -sfv libncurses++w.a /usr/lib/libncurses++.a  2>&1 >> ${DFILE}
rm -vf                     /usr/lib/libcursesw.so  2>&1 >> ${DFILE}
echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so 
ln -sfv libncurses.so      /usr/lib/libcurses.so  2>&1 >> ${DFILE}
ln -sfv libncursesw.a      /usr/lib/libcursesw.a  2>&1 >> ${DFILE}
ln -sfv libncurses.a       /usr/lib/libcurses.a  2>&1 >> ${DFILE}


#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
