#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=texinfo-5.0
tar -Jxf ${basename}.tar.xz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.xz"
cd ${basename}
##### Core things

#Configure
./configure --prefix=/usr 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make check

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

make TEXMF=/usr/share/texmf install-tex

cd /usr/share/info
rm -v dir 2>&1 >> ${DFILE}
for f in *
do install-info $f dir 2>/dev/null
done

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
