#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=dpkg-1.16.1.2ubuntu7.4
tar -jxf dpkg_1.16.1.2ubuntu7.4.tar.bz2 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.bz2"
cd ${basename}
##### Core things
patch -p0 < ../dpkg_arch.patch
#Configure
./configure --prefix=/usr/dpkg  2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#mv doc/Makefile doc/Makefile.bak
#sed 's/^all: /&# /g; s/^install: /&# /g' doc/Makefile.bak > doc/Makefile
#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make check

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

touch /usr/dpkg/var/lib/dpkg/status
touch /usr/dpkg/var/lib/dpkg/available

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
