#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=libnih_1.0.3.orig
tar -xf ${basename}.tar.gz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.gz"
cd libnih-1.0.3
##### Core things

#Configure
./configure --prefix=/usr 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make clean 2>&1 >> ${DFILE}
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make check

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"


#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf libnih-1.0.3  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
