#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=Linux-PAM-1.1.7
tar -jxf ${basename}.tar.bz2 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.bz2"
cd ${basename}
##### Core things

#Configure
./configure --prefix=/usr \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/Linux-PAM-1.1.7 \
            --disable-nis 2>&1 >> ${DFILE}
errorMsg $? "Failed to Configure ${basename}"

#Make
make 2>&1 >> ${DFILE}
errorMsg $? "Failed to make ${basename}"

#MAKE CHECK
# make check

make install 2>&1 >> ${DFILE}
errorMsg $? "Failed to install ${basename}"

chmod -v 4755 /sbin/unix_chkpwd

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed in `expr $end_time  - $start_time` seconds <=="
