#!/bin/sh
SBase=$1
SDir=$2
DFILE=$3
source ${SBase}/build_utils.sh

#echo "Logfile is $DFILE "
#UNTAR
start_time=`date +%s`
basename=cloudport_source
tar -xf ${basename}.tar.gz 2>&1 >> ${DFILE}
errorMsg $? "Failed to untar ${basename}.tar.xz"
cd ${basename}
##### Core things

./buildCloudPort.sh 2>&1 >> ${DFILE}

#back to sources dir
cd ${SDir} 2>&1 >> ${DFILE}
#remove folder(s)
rm -Rf ${basename}  2>&1 >> ${DFILE}

end_time=`date +%s`
logMsg "==> Completed( /build/${basename}.deb ) in `expr $end_time  - $start_time` seconds <=="
